version: '3'

services:

  nginx:
    image: nginx:alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf  
    command: [nginx-debug, '-g', 'daemon off;']
    links: 
      - clientes
      - productos
    ports:
      - "8080:80"

  clientes:
    build: ./clientes
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
 
  
  productos:
    build: ./productos
    healthcheck:
      test: curl --fail -s http://localhost:5000/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3


  

